export const STACK = {
  COMMON: 'COMMON',
  TAB: 'TAB',
  AUTH: 'AUTH',
};
export const ROUTES = {
  LOGIN: 'Login',
  LOGIN01: 'Login01',
  START_PAGE: 'StartPage',
  TITLE00: 'Title00',
  POLICY: 'Policy',
  SIGNUP00: 'Signup00',
  SIGNUP01: 'Signup01',
  SIGNUP02: 'Signup02',
  SIGNUP03: 'Signup03',
  APPROVAL: 'Approval',
  SECOND_AUTH_POPUP: 'SecondAuthPopup',
  SIGNUP_POPUP2: 'SignupPopUp2',
  NICE_AUTH: 'NiceAuth',
  SEARCH_IDPWD: 'SearchIdAndPwd',
  SHOP_INVENTORY: 'Inventory',
  Mileage_Shop: 'MileageShop',
  Mileage_History: 'MileageHistory',
  Limit_Info: 'LimitInfo',
  Auction_Detail: 'AuctionDetail',
  Mileage_Order: 'MileageOrder',
  Gifticon_Detail: 'GifticonDetail',
};
