export const STACK = {
  COMMON: 'COMMON',
  TAB: 'TAB',
  AUTH: 'AUTH',
};
export const ROUTES = {
  LOGIN: 'Login',
  LOGIN01: 'Login01',
  START_PAGE: 'StartPage',
  TITLE00: 'Title00',
  POLICY: 'Policy',
  SIGNUP00: 'Signup00',
  SIGNUP_CHECK: 'SignUp_Check',
  SIGNUP_ID: 'SignUp_ID',
  SIGNUP_PASSWORD: 'SignUp_Password',
  SIGNUP_IMAGE: 'SignUp_Image',
  SIGNUP_NICKNAME: 'SignUp_Nickname',
  SIGNUP_ADDINFO: 'SignUp_AddInfo',
  SIGNUP_INTEREST: 'SignUp_Interest',
  SIGNUP_INTRODUCE: 'SignUp_Introduce',
  SIGNUP_AUTH: 'SignUp_Auth',
  SIGNUP01: 'Signup01',
  SIGNUP02: 'Signup02',
  SIGNUP03: 'Signup03',
  APPROVAL: 'Approval',
  SECOND_AUTH_POPUP: 'SecondAuthPopup',
  SIGNUP_POPUP2: 'SignupPopUp2',
  NICE_AUTH: 'NiceAuth',
  SEARCH_IDPWD: 'SearchIdAndPwd',
  SHOP_INVENTORY: 'Inventory',
  Mileage_Shop: 'MileageShop',
  Mileage_History: 'MileageHistory',
  Limit_Info: 'LimitInfo',
  Auction_Detail: 'AuctionDetail',
  Mileage_Order: 'MileageOrder',
  Gifticon_Detail: 'GifticonDetail',
  ItemMatching: 'ItemMatching',
  MatchDetail: 'MatchDetail',

  PROFILE_ADDINFO: 'Profile_AddInfo',
  PROFILE_AUTH: 'Profile_AddInfo',
  PROFILE_INTEREST: 'Profile_Interest',
  PROFILE_INTRODUCE: 'Profile_Introduce',
};
